{% set name = "cramjam" %}
{% set version = "2.8.4" %}
{% set py_ver_split = PY_VER.split(".") %}
{% set major_minor = py_ver_split[ 0 ] + py_ver_split[ 1 ] %}

{% set target = "linux" %}      # [linux]
{% set target = "win" %}        # [win]
{% set target = "osx" %}        # [osx]

{% set arch = "ppc64le" %}      # [ppc64le]
{% set arch = "arm64" %}        # [arm64]
{% set arch = "x86_64" %}       # [x86_64]
{% set arch = "s390x" %}        # [s390x]
{% set arch = "win32" %}        # [win32]
{% set arch = "amd64" %}        # [win64]
{% set arch = "aarch64" %}      # [aarch64]
{% set arch = "i686" %}         # [i686]
{% set arch = "armv7l" %}       # [armv7l]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad8bec85b46283330214f4367805e6f56e04ce25a030a2c6a4b127437d006fcf

build:
  number: 0
  script_env:
    VERSION: {{ version }}
    PYTHON: {{ PYTHON }}
    MAJOR_MINOR: {{ major_minor }}
    ARCH: {{ arch }}
    TARGET: {{ target }}
  script: |
    bash build.sh

requirements:
  build:
    - python
    - m2-bash  # [win]
    - maturin
    - pip
    - curl
  host:
    - python
    - maturin
    - pip
  run:
    - python

test:
  imports:
    - cramjam

about:
  home: https://github.com/milesgranger/pyrus-cramjam
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: python bindings to rust-implemented compression
  description: Extremely thin Python bindings to de/compression algorithms in Rust. 
  doc_url: https://docs.rs/cramjam

extra:
  recipe-maintainers:
    - martindurant
    - milesgranger
