schema_version: 1

context:
  name: cramjam
  version: "2.11.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 5c82500ed91605c2d9781380b378397012e25127e89d64f460fea6aeac4389b4

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin
        - toml
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - make
    - cmake
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin
    - toml
  run:
    - python

tests:
  - python:
      imports:
        - cramjam
      pip_check: true
      python_version: ${{ python }}

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: python bindings to rust-implemented compression
  # The remaining entries in this section are optional, but recommended.
  description: |
    Extremely thin Python bindings to de/compression algorithms in Rust.
    Allows for using algorithms such as Snappy, without any system dependencies.
    This is handy when being used in environments like AWS Lambda,
    where installing packages like python-snappy becomes difficult because of
    system level dependencies.
  homepage: https://github.com/milesgranger/pyrus-cramjam
  documentation: https://docs.rs/cramjam

extra:
  recipe-maintainers:
    - martindurant
    - milesgranger
